FROM openjdk:8-jdk
# 设置工作目录
WORKDIR /app

# 复制项目的源代码到容器中
COPY . /app

WORKDIR /app

# 复制构建的 jar 文件到容器中
COPY target/video-core-1.0.0.jar /app/video-core.jar

# 暴露应用运行的端口
EXPOSE 8080
EXPOSE 7071

# 运行应用
ENTRYPOINT ["java", "-jar", "/app/video-core.jar"]